services:
    backend:
      build: backend
      command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
      volumes:
        - ./backend:/app
      ports:
        - "8000:8000" # TODO: remove when reverse proxy is added
      env_file:
        - .env
      depends_on:
        db:
          condition: service_healthy
    frontend:
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        restart: always
        volumes:
            - ./frontend:/app
    db:
        image: postgres:12
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./db:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
          interval: 5s
          timeout: 5s
          retries: 5
    nginx:
        image: nginx:1.17
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - frontend
            - db
    minio:
      image: bitnami/minio
      restart: always
      ports:
        - '9000:9000'
        - '9001:9001'
      volumes:
        - ./blob:/data
      environment:
        - MINIO_ROOT_USER=your_username
        - MINIO_ROOT_PASSWORD=your_password