# Generated by Django 5.0.6 on 2024-09-02 15:18

import Common.enums.Languages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("production_year", models.PositiveSmallIntegerField()),
                ("thumbnail", models.ImageField(upload_to="")),
                ("imdb_rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("director", models.CharField(max_length=200)),
                ("producer", models.CharField(max_length=200)),
                ("cast", models.CharField(max_length=200)),
                ("duration", models.PositiveSmallIntegerField()),
                ("file", models.FileField(upload_to="")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_watched", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("FRENCH", "french"), ("ENGLISH", "english")],
                        default=Common.enums.Languages.Languages["ENGLISH"],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="movies.video",
                    ),
                ),
            ],
        ),
    ]
