# Generated by Django 5.0.6 on 2024-09-06 10:33

from django.db import migrations, models

import Common.enums.Languages


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtitle",
            name="language",
            field=models.CharField(
                choices=[("french", "FRENCH"), ("english", "ENGLISH")],
                default=Common.enums.Languages.Languages["ENGLISH"],
                max_length=10,
            ),
        ),
    ]
