// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type {
	RootRetrieveData,
	SearchRetrieveData,
	SearchGenresRetrieveData,
	SearchPopularRetrieveData,
	SearchTrendingRetrieveData,
} from './types.gen';

export const client = createClient(createConfig());

export const rootRetrieve = <ThrowOnError extends boolean = false>(
	options?: Options<RootRetrieveData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		...options,
		url: '/api/v1/',
	});
};

export const searchRetrieve = <ThrowOnError extends boolean = false>(
	options: Options<SearchRetrieveData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		...options,
		url: '/api/v1/search/',
	});
};

export const searchGenresRetrieve = <ThrowOnError extends boolean = false>(
	options?: Options<SearchGenresRetrieveData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		...options,
		url: '/api/v1/search/genres/',
	});
};

export const searchPopularRetrieve = <ThrowOnError extends boolean = false>(
	options?: Options<SearchPopularRetrieveData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		...options,
		url: '/api/v1/search/popular/',
	});
};

export const searchTrendingRetrieve = <ThrowOnError extends boolean = false>(
	options?: Options<SearchTrendingRetrieveData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		...options,
		url: '/api/v1/search/trending/',
	});
};
