// This file is auto-generated by @hey-api/openapi-ts

export type RootRetrieveData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/';
};

export type RootRetrieveResponses = {
	/**
	 * No response body
	 */
	200: unknown;
};

export type SearchRetrieveData = {
	body?: never;
	path?: never;
	query: {
		language?: string;
		page?: number;
		primary_release_year?: number;
		query: string;
		region?: string;
		year?: number;
	};
	url: '/api/v1/search/';
};

export type SearchRetrieveResponses = {
	/**
	 * No response body
	 */
	200: unknown;
};

export type SearchGenresRetrieveData = {
	body?: never;
	path?: never;
	query?: {
		language?: string;
		page?: number;
	};
	url: '/api/v1/search/genres/';
};

export type SearchGenresRetrieveResponses = {
	/**
	 * No response body
	 */
	200: unknown;
};

export type SearchPopularRetrieveData = {
	body?: never;
	path?: never;
	query?: {
		language?: string;
		page?: number;
	};
	url: '/api/v1/search/popular/';
};

export type SearchPopularRetrieveResponses = {
	/**
	 * No response body
	 */
	200: unknown;
};

export type SearchTrendingRetrieveData = {
	body?: never;
	path?: never;
	query?: {
		language?: string;
		page?: number;
	};
	url: '/api/v1/search/trending/';
};

export type SearchTrendingRetrieveResponses = {
	/**
	 * No response body
	 */
	200: unknown;
};
