version: 2.1

orbs:
  node: circleci/node@5.3.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
      resource_class: medium
    steps:
      - checkout
      - run:
          command: make env && make
          name: Build app
  build_and_test_frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd frontend && npm ci
          name: Install dependencies
      - run:
          command: cd frontend && npm run check-format
          name: Check format
      - run:
          command: cd frontend && npm run lint
          name: Lint


workflows:
  build app:
    jobs:
      - build
      - build_and_test_frontend
