version: 2.1

orbs:
  node: circleci/node@6.1.0
  python: circleci/python@2.1.1


jobs:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
      resource_class: medium
    steps:
      - checkout
      - run:
          command: make env && make
          name: Build app
  build_and_test_frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd frontend && npm ci
          name: Install dependencies
      - run:
          command: cd frontend && npm run check-format
          name: Check format
      - run:
          command: cd frontend && npm run lint
          name: Lint
  build_and_test_backend:
    executor: python/default
    steps:
      - checkout
      - run:
          command:  cd backend && python manage.py check
          name: Check
      - run:
          command: cd backend && python manage.py makemigrations --check
          name: Check migrations
      - run:
          command: cd backend && pre-commit run --all-files
          name: Pre-commit

workflows:
  build app:
    jobs:
      - build
      - build_and_test_frontend
      - build_and_test_backend
