version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
      resource_class: medium
    steps:
      - checkout
      - run: make env && make
  build_and_test_frontend:
    executor: node/default
    working_directory: ~/frontend
    steps:
      - checkout
      - run: 
          command: pwd && ls -la
          name: debug
      - run: 
          command: npm ci
          name: Install dependencies
      - run:  
          command: npm run check-format
          name: Check format
      - run:
          command: npm run lint
          name: Lint
        

workflows:
  build app:
    jobs:
      - build
      - build_and_test_frontend
