version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
      resource_class: medium
    steps:
      - checkout
      - run: make env && make
  build_and_test_frontend:
    executor: node/default
    steps:
      - checkout
      - run: 
          command: cd frontend && npm ci
          name: Install dependencies
      - run: npm run lint 
      - run:  npm run check-format
        

workflows:
  build app:
    jobs:
      - build
  build and test frontend:
    jobs:
      - build_and_test_frontend
