version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
      resource_class: medium
    steps:
      - checkout
      - run: make env && make

workflows:
  build app:
    jobs:
      - build
