# Generated by Django 5.0.6 on 2024-09-02 15:18

from django.db import migrations, models

import Common.enums.Languages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("profile_picture", models.ImageField(upload_to="")),
                (
                    "prefered_lang",
                    models.CharField(
                        choices=[("FRENCH", "french"), ("ENGLISH", "english")],
                        default=Common.enums.Languages.Languages["ENGLISH"],
                        max_length=10,
                    ),
                ),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "watched",
                    models.ManyToManyField(
                        related_name="watched_by", to="movies.video"
                    ),
                ),
            ],
        ),
    ]
